,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,body,closed_by,reactions,timeline_url,performed_via_github_app,state_reason,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas/issues/60023,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60023/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60023/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60023/events,https://github.com/pandas-dev/pandas/issues/60023,2582233739,I_kwDOAA0YD86Z6cKL,60023,"BUG: ""Python int too large"" in maybe_convert_objects with numpy 1.26","{'login': 'bemoody', 'id': 7748246, 'node_id': 'MDQ6VXNlcjc3NDgyNDY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7748246?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/bemoody', 'html_url': 'https://github.com/bemoody', 'followers_url': 'https://api.github.com/users/bemoody/followers', 'following_url': 'https://api.github.com/users/bemoody/following{/other_user}', 'gists_url': 'https://api.github.com/users/bemoody/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/bemoody/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/bemoody/subscriptions', 'organizations_url': 'https://api.github.com/users/bemoody/orgs', 'repos_url': 'https://api.github.com/users/bemoody/repos', 'events_url': 'https://api.github.com/users/bemoody/events{/privacy}', 'received_events_url': 'https://api.github.com/users/bemoody/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-11T21:47:06Z,2024-10-11T21:52:51Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.

### Reproducible Example

`pip install numpy==1.26.4 pandas==2.2.3`

```
import numpy, pandas
numpy._set_promotion_state(""weak_and_warn"")
x = pandas.DataFrame({""x"": [1]})
print(x)
```

### Issue Description

If using numpy 1.26, and numpy is set to ""weak"" or ""weak_and_warn"" promotion mode (meant to be compatible with the behavior of numpy 2.x), this causes internal pandas functions to fail.

For example, the above command to print a trivial DataFrame results in:
```
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""/home/benjamin/v/lib/python3.11/site-packages/pandas/core/frame.py"", line 1214, in __repr__
    return self.to_string(**repr_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/benjamin/v/lib/python3.11/site-packages/pandas/util/_decorators.py"", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File ""/home/benjamin/v/lib/python3.11/site-packages/pandas/core/frame.py"", line 1394, in to_string
    return fmt.DataFrameRenderer(formatter).to_string(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/benjamin/v/lib/python3.11/site-packages/pandas/io/formats/format.py"", line 962, in to_string
    string = string_formatter.to_string()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/benjamin/v/lib/python3.11/site-packages/pandas/io/formats/string.py"", line 29, in to_string
    text = self._get_string_representation()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/benjamin/v/lib/python3.11/site-packages/pandas/io/formats/string.py"", line 53, in _get_string_representation
    return self._fit_strcols_to_terminal_width(strcols)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/benjamin/v/lib/python3.11/site-packages/pandas/io/formats/string.py"", line 163, in _fit_strcols_to_terminal_width
    col_lens = Series([Series(ele).str.len().max() for ele in strcols])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/benjamin/v/lib/python3.11/site-packages/pandas/core/series.py"", line 584, in __init__
    data = sanitize_array(data, index, dtype, copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/benjamin/v/lib/python3.11/site-packages/pandas/core/construction.py"", line 654, in sanitize_array
    subarr = maybe_convert_platform(data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""/home/benjamin/v/lib/python3.11/site-packages/pandas/core/dtypes/cast.py"", line 138, in maybe_convert_platform
    arr = lib.maybe_convert_objects(arr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ""lib.pyx"", line 2602, in pandas._libs.lib.maybe_convert_objects
OverflowError: Python int too large to convert to C long
```

This doesn't happen with numpy 1.26 in its default ""legacy"" mode.  It doesn't happen with numpy 2.x in either ""legacy"" or ""weak"" mode.

More information about numpy 1.x versus 2.x and promotion modes is documented here: https://numpy.org/devdocs/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion

### Expected Behavior

`print(pandas.DataFrame({""x"": [1]}))` should not crash.  It should work properly regardless of the global numpy promotion setting.

### Installed Versions

<details>

```
INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.11.2
python-bits           : 64
OS                    : Linux
OS-release            : 6.1.0-7-amd64
Version               : #1 SMP PREEMPT_DYNAMIC Debian 6.1.20-2 (2023-04-08)
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.3
numpy                 : 1.26.4
pytz                  : 2024.2
dateutil              : 2.9.0.post0
pip                   : 23.0.1
Cython                : None
sphinx                : None
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None
```

</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60023/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60023/timeline,,,,
1,https://api.github.com/repos/pandas-dev/pandas/issues/60018,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60018/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60018/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60018/events,https://github.com/pandas-dev/pandas/issues/60018,2580151461,I_kwDOAA0YD86Zyfyl,60018,"BUG: when using id_vars in .melt(), the id_vars does not recognize the column name in a multiIndex dataframe","{'login': 'ivan-marroquin', 'id': 28459534, 'node_id': 'MDQ6VXNlcjI4NDU5NTM0', 'avatar_url': 'https://avatars.githubusercontent.com/u/28459534?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ivan-marroquin', 'html_url': 'https://github.com/ivan-marroquin', 'followers_url': 'https://api.github.com/users/ivan-marroquin/followers', 'following_url': 'https://api.github.com/users/ivan-marroquin/following{/other_user}', 'gists_url': 'https://api.github.com/users/ivan-marroquin/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ivan-marroquin/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ivan-marroquin/subscriptions', 'organizations_url': 'https://api.github.com/users/ivan-marroquin/orgs', 'repos_url': 'https://api.github.com/users/ivan-marroquin/repos', 'events_url': 'https://api.github.com/users/ivan-marroquin/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ivan-marroquin/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-10-11T00:48:34Z,2024-10-11T00:48:34Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd
import yfinance as yf
from datetime import date, timedelta

end_date= date.today().strftime(""%Y-%m-%d"")
start_date= (date.today() - timedelta(days= 365)).strftime(""%Y-%m-%d"")

tickers= ['RELIANCE.NS', 'TCS.NS', 'INFY.NS', 'HDFCBANK.NS']

data= yf.download(tickers, start= start_date, end= end_date)

data= data.reset_index()

data_melted= data.melt(id_vars= ['Date'], var_name= ['Attribute', 'Ticker'])
```


### Issue Description

KeyError                                  Traceback (most recent call last)
Cell In [19], [line 15](vscode-notebook-cell:?execution_count=19&line=15)
     [11](vscode-notebook-cell:?execution_count=19&line=11) data= data.reset_index()
     [13](vscode-notebook-cell:?execution_count=19&line=13) # melt the DataFrame to make it long format where each row is a 
     [14](vscode-notebook-cell:?execution_count=19&line=14) # unique combination of Date, Ticker, and attributes
---> [15](vscode-notebook-cell:?execution_count=19&line=15) data_melted= data.melt(id_vars= ['Date'], var_name= ['Attribute', 'Ticker'])
     [17](vscode-notebook-cell:?execution_count=19&line=17) # pivot the melted DataFrame to have the attributes (Open, High, Low, etc.) as columns
     [18](vscode-notebook-cell:?execution_count=19&line=18) data_pivoted= data_melted.pivot_table(index= ['Date', 'Ticker'], 
     [19](vscode-notebook-cell:?execution_count=19&line=19)                                       columns= 'Attribute', values= 'value', 
     [20](vscode-notebook-cell:?execution_count=19&line=20)                                       aggfunc= 'first')

File ~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9942, in DataFrame.melt(self, id_vars, value_vars, var_name, value_name, col_level, ignore_index)
   [9932](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9932) @Appender(_shared_docs[""melt""] % {""caller"": ""df.melt("", ""other"": ""melt""})
   [9933](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9933) def melt(
   [9934](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9934)     self,
   (...)
   [9940](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9940)     ignore_index: bool = True,
   [9941](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9941) ) -> DataFrame:
-> [9942](https://file+.vscode-resource.vscode-cdn.net/home/ivan_phd/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9942)     return melt(
   [9943](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9943)         self,
   [9944](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9944)         id_vars=id_vars,
   [9945](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9945)         value_vars=value_vars,
   [9946](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9946)         var_name=var_name,
   [9947](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/frame.py:9947)         value_name=value_name,
...
     [77](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/reshape/melt.py:77)     )
     [78](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/reshape/melt.py:78) if value_vars_was_not_none:
     [79](https://file+.vscode-resource.vscode-cdn.net/home/ivan/python_fun/Data_Analytics/~/python_3.9.0/lib/python3.9/site-packages/pandas/core/reshape/melt.py:79)     frame = frame.iloc[:, algos.unique(idx)]

KeyError: ""The following id_vars or value_vars are not present in the DataFrame: ['Date']""

### Expected Behavior

The melt function should generate a  DataFrame to make it long format where each row is a unique combination of Date, Ticker, and attributes

### Installed Versions

<details>
INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.9.0.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.5.0-25-generic
Version               : #25~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Feb 20 16:09:15 UTC 2
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 1.23.3
pytz                  : 2024.2
dateutil              : 2.8.2
setuptools            : 59.8.0
pip                   : 22.3.1
Cython                : 0.29.32
pytest                : None
hypothesis            : None
sphinx                : 5.1.1
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 4.9.1
html5lib              : 1.1
pymysql               : None
psycopg2              : None
jinja2                : 3.1.2
IPython               : 8.5.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.6.1
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : 2.10.1
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
pyarrow               : 16.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : 2024.6.1
scipy                 : 1.13.1
sqlalchemy            : 2.0.31
tables                : None
tabulate              : 0.9.0
xarray                : 2024.6.0
xlrd                  : None
zstandard             : None
tzdata                : 2023.3
qtpy                  : None
pyqt5                 : None

Python 3.9.0
</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60018/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60018/timeline,,,,
2,https://api.github.com/repos/pandas-dev/pandas/issues/60017,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60017/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60017/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60017/events,https://github.com/pandas-dev/pandas/issues/60017,2580014615,I_kwDOAA0YD86Zx-YX,60017,QST: how can I save my sparse dataframe with indexes and columns to a format other than .pkl?,"{'login': 'michelkluger', 'id': 50880307, 'node_id': 'MDQ6VXNlcjUwODgwMzA3', 'avatar_url': 'https://avatars.githubusercontent.com/u/50880307?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/michelkluger', 'html_url': 'https://github.com/michelkluger', 'followers_url': 'https://api.github.com/users/michelkluger/followers', 'following_url': 'https://api.github.com/users/michelkluger/following{/other_user}', 'gists_url': 'https://api.github.com/users/michelkluger/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/michelkluger/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/michelkluger/subscriptions', 'organizations_url': 'https://api.github.com/users/michelkluger/orgs', 'repos_url': 'https://api.github.com/users/michelkluger/repos', 'events_url': 'https://api.github.com/users/michelkluger/events{/privacy}', 'received_events_url': 'https://api.github.com/users/michelkluger/received_events', 'type': 'User', 'site_admin': False}","[{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0NDUzNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question', 'name': 'Usage Question', 'color': '0052cc', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-10-10T23:02:46Z,2024-10-10T23:02:46Z,,NONE,,"### Research

- [X] I have searched the [[pandas] tag](https://stackoverflow.com/questions/tagged/pandas) on StackOverflow for similar questions.

- [X] I have asked my usage related question on [StackOverflow](https://stackoverflow.com).


### Link to question on StackOverflow

https://stackoverflow.com/questions/60956268/save-sparse-pandas-dataframe-to-different-file-types

### Question about pandas

I want have sparse dataframe structure saved in one file (to avoid proliferation of files)

how can I write and read and get the same sparse df? any alternative to pickle?",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60017/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60017/timeline,,,,
3,https://api.github.com/repos/pandas-dev/pandas/issues/60016,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60016/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60016/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60016/events,https://github.com/pandas-dev/pandas/issues/60016,2579964188,I_kwDOAA0YD86ZxyEc,60016,BUILD: pandas fails to install with python-freethreading 3.13.0 final release,"{'login': 'djakubiec', 'id': 21962962, 'node_id': 'MDQ6VXNlcjIxOTYyOTYy', 'avatar_url': 'https://avatars.githubusercontent.com/u/21962962?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/djakubiec', 'html_url': 'https://github.com/djakubiec', 'followers_url': 'https://api.github.com/users/djakubiec/followers', 'following_url': 'https://api.github.com/users/djakubiec/following{/other_user}', 'gists_url': 'https://api.github.com/users/djakubiec/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/djakubiec/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/djakubiec/subscriptions', 'organizations_url': 'https://api.github.com/users/djakubiec/orgs', 'repos_url': 'https://api.github.com/users/djakubiec/repos', 'events_url': 'https://api.github.com/users/djakubiec/events{/privacy}', 'received_events_url': 'https://api.github.com/users/djakubiec/received_events', 'type': 'User', 'site_admin': False}","[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNTA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Build', 'name': 'Build', 'color': '75507B', 'default': False, 'description': 'Library building on various platforms'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2024-10-10T22:25:38Z,2024-10-10T22:25:38Z,,NONE,,"### Installation check

- [X] I have read the [installation guide](https://pandas.pydata.org/pandas-docs/stable/getting_started/install.html#installing-pandas).


### Platform

Linux-5.4.0-172-generic-x86_64-with-glibc2.31

### Installation Method

conda install

### pandas Version

2.2.3

### Python Version

3.13.0 freethreading

### Installation Logs

<details>

```
⇒  conda create -y --name python313t --channel conda-forge python-freethreading pandas
Channels:
 - conda-forge
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package pandas-0.20.3-py27h820b67f_2 requires python >=2.7,<2.8.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ pandas is installable with the potential options
│  ├─ pandas [0.20.3|0.21.0|...|0.24.2] would require
│  │  └─ python >=2.7,<2.8.0a0 , which can be installed;
│  ├─ pandas [0.17.0|0.17.1|...|1.0.1], which can be installed;
│  ├─ pandas [1.0.2|1.0.3|...|1.1.5] would require
│  │  ├─ python >=3.6,<3.7.0a0 , which can be installed;
│  │  └─ python_abi 3.6.* *_cp36m, which can be installed;
│  ├─ pandas [1.0.2|1.0.3|...|1.3.5] would require
│  │  ├─ python >=3.7,<3.8.0a0 , which can be installed;
│  │  └─ python_abi 3.7.* *_cp37m, which can be installed;
│  ├─ pandas [1.0.2|1.0.3|...|2.0.3] would require
│  │  ├─ python >=3.8,<3.9.0a0 , which can be installed;
│  │  └─ python_abi 3.8.* *_cp38, which can be installed;
│  ├─ pandas [1.0.3|1.0.4|...|1.1.5] would require
│  │  └─ python_abi 3.6 *_pypy36_pp73, which requires
│  │     └─ python 3.6.* *_73_pypy, which can be installed;
│  ├─ pandas [1.1.3|1.1.4|...|2.2.3] would require
│  │  ├─ python >=3.9,<3.10.0a0 , which can be installed;
│  │  └─ python_abi 3.9.* *_cp39, which can be installed;
│  ├─ pandas [1.2.0|1.2.1|...|1.3.5] would require
│  │  └─ python_abi 3.7 *_pypy37_pp73, which requires
│  │     └─ python 3.7.* *_73_pypy, which can be installed;
│  ├─ pandas [1.3.4|1.3.5|...|2.2.3] would require
│  │  ├─ python >=3.10,<3.11.0a0 , which can be installed;
│  │  └─ python_abi 3.10.* *_cp310, which can be installed;
│  ├─ pandas [1.4.2|1.4.3|...|2.0.3] would require
│  │  └─ python_abi 3.8 *_pypy38_pp73, which requires
│  │     └─ python 3.8.* *_73_pypy, which can be installed;
│  ├─ pandas [1.4.2|1.4.3|...|2.2.2] would require
│  │  └─ python_abi 3.9 *_pypy39_pp73, which requires
│  │     └─ python 3.9.* *_73_pypy, which can be installed;
│  ├─ pandas [1.5.1|1.5.2|...|2.2.3] would require
│  │  ├─ python >=3.11,<3.12.0a0 , which can be installed;
│  │  └─ python_abi 3.11.* *_cp311, which can be installed;
│  ├─ pandas [2.1.1|2.1.2|...|2.2.3] would require
│  │  └─ python_abi 3.12.* *_cp312, which can be installed;
│  ├─ pandas 2.2.3 would require
│  │  └─ python_abi 3.11.* *_cp311, which can be installed;
│  ├─ pandas 2.2.3 would require
│  │  ├─ python >=3.13.0rc2,<3.14.0a0  but there are no viable options
│  │  │  ├─ python 3.13.0 conflicts with any installable versions previously reported;
│  │  │  └─ python [3.13.0rc1|3.13.0rc2|3.13.0rc3] would require
│  │  │     └─ _python_rc, which does not exist (perhaps a missing channel);
│  │  └─ python_abi 3.13.* *_cp313 with the potential options
│  │     ├─ python_abi 3.13 would require
│  │     │  └─ python 3.13.* *_cpython, which conflicts with any installable versions previously reported;
│  │     └─ python_abi 3.13 would require
│  │        └─ python 3.13.* *_cp313, which can be installed;
│  ├─ pandas [0.20.3|0.21.0|...|0.23.4] would require
│  │  └─ python >=3.5,<3.6.0a0 , which can be installed;
│  ├─ pandas [0.20.3|0.21.0|...|1.1.5] would require
│  │  └─ python >=3.6,<3.7.0a0 , which can be installed;
│  ├─ pandas [0.23.2|0.23.3|...|1.3.5] would require
│  │  └─ python >=3.7,<3.8.0a0 , which can be installed;
│  ├─ pandas [0.25.3|1.0.0|...|2.0.3] would require
│  │  └─ python >=3.8,<3.9.0a0 , which can be installed;
│  ├─ pandas [1.1.3|1.1.5|...|2.2.2] would require
│  │  └─ python >=3.9,<3.10.0a0 , which can be installed;
│  ├─ pandas 1.3.0 would require
│  │  └─ python >=3.7.1,<3.8.0a0 , which can be installed;
│  ├─ pandas [1.4.1|1.4.2|...|2.2.2] would require
│  │  └─ python >=3.10,<3.11.0a0 , which can be installed;
│  ├─ pandas [1.5.2|1.5.3|...|2.2.2] would require
│  │  └─ python >=3.11,<3.12.0a0 , which can be installed;
│  └─ pandas [2.1.1|2.1.4|2.2.1|2.2.2] would require
│     └─ python >=3.12,<3.13.0a0 , which can be installed;
└─ python-freethreading is not installable because there are no viable options
   ├─ python-freethreading [3.13.0rc1|3.13.0rc2] would require
   │  └─ python_abi * *_cp313t but there are no viable options
   │     ├─ python_abi 3.13 would require
   │     │  └─ python 3.13.* *_cp313t, which conflicts with any installable versions previously reported;
   │     └─ python_abi 3.13, which cannot be installed (as previously explained);
   └─ python-freethreading [3.13.0|3.13.0rc2|3.13.0rc3] would require
      ├─ cpython 3.13.0.*  but there are no viable options
      │  ├─ cpython [3.13.0|3.13.0rc1|3.13.0rc2|3.13.0rc3] would require
      │  │  └─ python 3.13.0.*  but there are no viable options
      │  │     ├─ python 3.13.0 conflicts with any installable versions previously reported;
      │  │     └─ python [3.13.0rc1|3.13.0rc2|3.13.0rc3], which cannot be installed (as previously explained);
      │  └─ cpython 3.13.0 would require
      │     ├─ python 3.13.0.*  but there are no viable options
      │     │  ├─ python 3.13.0 conflicts with any installable versions previously reported;
      │     │  └─ python [3.13.0rc1|3.13.0rc2|3.13.0rc3], which cannot be installed (as previously explained);
      │     └─ python_abi * *_cp313 with the potential options
      │        ├─ python_abi 3.13, which cannot be installed (as previously explained);
      │        └─ python_abi 3.13, which can be installed (as previously explained);
      └─ python_abi * *_cp313t, which cannot be installed (as previously explained).

```
</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60016/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60016/timeline,,,,
4,https://api.github.com/repos/pandas-dev/pandas/issues/60010,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60010/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60010/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60010/events,https://github.com/pandas-dev/pandas/issues/60010,2576524873,I_kwDOAA0YD86ZkqZJ,60010,DOC: Update contributing documentation with code coverage details,"{'login': 'd33bs', 'id': 3738008, 'node_id': 'MDQ6VXNlcjM3MzgwMDg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3738008?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/d33bs', 'html_url': 'https://github.com/d33bs', 'followers_url': 'https://api.github.com/users/d33bs/followers', 'following_url': 'https://api.github.com/users/d33bs/following{/other_user}', 'gists_url': 'https://api.github.com/users/d33bs/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/d33bs/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/d33bs/subscriptions', 'organizations_url': 'https://api.github.com/users/d33bs/orgs', 'repos_url': 'https://api.github.com/users/d33bs/repos', 'events_url': 'https://api.github.com/users/d33bs/events{/privacy}', 'received_events_url': 'https://api.github.com/users/d33bs/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}]",open,False,,[],,3,2024-10-09T17:31:31Z,2024-10-09T21:39:50Z,,NONE,,"### Pandas version checks

- [X] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)


### Location of the documentation

https://pandas.pydata.org/docs/development/contributing_codebase.html

### Documentation problem

Thanks for the great work on Pandas! I was interested in finding out how Pandas measures code coverage and found that there doesn't seem to be much content yet on how to do this for the project. There's a dead link at https://pandas-coverage-12d2130077bc.herokuapp.com/ for the link mentioned in the content `(tip: you can use the [pandas-coverage app](https://pandas-coverage-12d2130077bc.herokuapp.com/))`. 

I also noticed there's a `codecov.yml` file in the project so I looked this up manually by viewing: https://app.codecov.io/github/pandas-dev/pandas . This looks like a nice way to measure code coverage for the project which has already been configured, but isn't already mentioned within documentation (perhaps in addition to the already mentioned tool, once the link is fixed).

### Suggested fix for documentation

I suggest adding the Codecov link somewhere in the contributing documentation and fixing the broken link for the `pandas-coverage app` (multiple measurements / perspectives could be helpful). ",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60010/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60010/timeline,,,,
5,https://api.github.com/repos/pandas-dev/pandas/issues/60009,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/60009/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/60009/comments,https://api.github.com/repos/pandas-dev/pandas/issues/60009/events,https://github.com/pandas-dev/pandas/issues/60009,2576509317,I_kwDOAA0YD86ZkmmF,60009,DOC: document that DataFrame and Series round() only affect numeric columns,"{'login': 'sfc-gh-mvashishtha', 'id': 149194323, 'node_id': 'U_kgDOCOSGUw', 'avatar_url': 'https://avatars.githubusercontent.com/u/149194323?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sfc-gh-mvashishtha', 'html_url': 'https://github.com/sfc-gh-mvashishtha', 'followers_url': 'https://api.github.com/users/sfc-gh-mvashishtha/followers', 'following_url': 'https://api.github.com/users/sfc-gh-mvashishtha/following{/other_user}', 'gists_url': 'https://api.github.com/users/sfc-gh-mvashishtha/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sfc-gh-mvashishtha/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sfc-gh-mvashishtha/subscriptions', 'organizations_url': 'https://api.github.com/users/sfc-gh-mvashishtha/orgs', 'repos_url': 'https://api.github.com/users/sfc-gh-mvashishtha/repos', 'events_url': 'https://api.github.com/users/sfc-gh-mvashishtha/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sfc-gh-mvashishtha/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2024-10-09T17:22:06Z,2024-10-10T21:37:30Z,,NONE,,"[DataFrame.round](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.round.html) and `Series.round` seem to ignore non-numeric columns, but their documentation doesn't mention that.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/60009/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/60009/timeline,,,,
6,https://api.github.com/repos/pandas-dev/pandas/issues/59997,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59997/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59997/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59997/events,https://github.com/pandas-dev/pandas/pull/59997,2570805315,PR_kwDOAA0YD8591fRr,59997,BUG: fix #59965 skipna=True operations don't skip NaN in FloatingArrays,"{'login': 'cooolheater', 'id': 184128544, 'node_id': 'U_kgDOCvmUIA', 'avatar_url': 'https://avatars.githubusercontent.com/u/184128544?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/cooolheater', 'html_url': 'https://github.com/cooolheater', 'followers_url': 'https://api.github.com/users/cooolheater/followers', 'following_url': 'https://api.github.com/users/cooolheater/following{/other_user}', 'gists_url': 'https://api.github.com/users/cooolheater/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/cooolheater/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/cooolheater/subscriptions', 'organizations_url': 'https://api.github.com/users/cooolheater/orgs', 'repos_url': 'https://api.github.com/users/cooolheater/repos', 'events_url': 'https://api.github.com/users/cooolheater/events{/privacy}', 'received_events_url': 'https://api.github.com/users/cooolheater/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-07T15:36:46Z,2024-10-11T12:09:18Z,,NONE,,"    - Issue: The skipna was not properly handled for BaseMaskedArray
    - Fix: Added mask for NA values
    - Test: Added test to series/test_reductions since the test uses

- [X] closes #59965
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59997/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59997/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59997', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59997', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59997.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59997.patch', 'merged_at': None}"
7,https://api.github.com/repos/pandas-dev/pandas/issues/59994,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59994/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59994/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59994/events,https://github.com/pandas-dev/pandas/pull/59994,2570374005,PR_kwDOAA0YD8590FEn,59994,enhancement on times.py,"{'login': 'Lzforevr', 'id': 139556927, 'node_id': 'U_kgDOCFF4Pw', 'avatar_url': 'https://avatars.githubusercontent.com/u/139556927?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Lzforevr', 'html_url': 'https://github.com/Lzforevr', 'followers_url': 'https://api.github.com/users/Lzforevr/followers', 'following_url': 'https://api.github.com/users/Lzforevr/following{/other_user}', 'gists_url': 'https://api.github.com/users/Lzforevr/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Lzforevr/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Lzforevr/subscriptions', 'organizations_url': 'https://api.github.com/users/Lzforevr/orgs', 'repos_url': 'https://api.github.com/users/Lzforevr/repos', 'events_url': 'https://api.github.com/users/Lzforevr/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Lzforevr/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-07T12:59:45Z,2024-10-07T12:59:45Z,,NONE,,"- [ ] closes #59931  (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59994/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59994/timeline,,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59994', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59994', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59994.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59994.patch', 'merged_at': None}"
8,https://api.github.com/repos/pandas-dev/pandas/issues/59993,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59993/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59993/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59993/events,https://github.com/pandas-dev/pandas/pull/59993,2570365077,PR_kwDOAA0YD8590DHV,59993,"Enhancements in numeric.py for 0x,0o,0b","{'login': 'Lzforevr', 'id': 139556927, 'node_id': 'U_kgDOCFF4Pw', 'avatar_url': 'https://avatars.githubusercontent.com/u/139556927?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Lzforevr', 'html_url': 'https://github.com/Lzforevr', 'followers_url': 'https://api.github.com/users/Lzforevr/followers', 'following_url': 'https://api.github.com/users/Lzforevr/following{/other_user}', 'gists_url': 'https://api.github.com/users/Lzforevr/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Lzforevr/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Lzforevr/subscriptions', 'organizations_url': 'https://api.github.com/users/Lzforevr/orgs', 'repos_url': 'https://api.github.com/users/Lzforevr/repos', 'events_url': 'https://api.github.com/users/Lzforevr/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Lzforevr/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-07T12:56:10Z,2024-10-07T12:56:15Z,,NONE,,"- [x] closes #59207 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59993/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59993/timeline,,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59993', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59993', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59993.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59993.patch', 'merged_at': None}"
9,https://api.github.com/repos/pandas-dev/pandas/issues/59987,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59987/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59987/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59987/events,https://github.com/pandas-dev/pandas/pull/59987,2569446341,PR_kwDOAA0YD859xDGj,59987,Fix: Change None values to NaN in combine_first method for better han…,"{'login': 'Lavishgangwani', 'id': 154001570, 'node_id': 'U_kgDOCS3gog', 'avatar_url': 'https://avatars.githubusercontent.com/u/154001570?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Lavishgangwani', 'html_url': 'https://github.com/Lavishgangwani', 'followers_url': 'https://api.github.com/users/Lavishgangwani/followers', 'following_url': 'https://api.github.com/users/Lavishgangwani/following{/other_user}', 'gists_url': 'https://api.github.com/users/Lavishgangwani/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Lavishgangwani/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Lavishgangwani/subscriptions', 'organizations_url': 'https://api.github.com/users/Lavishgangwani/orgs', 'repos_url': 'https://api.github.com/users/Lavishgangwani/repos', 'events_url': 'https://api.github.com/users/Lavishgangwani/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Lavishgangwani/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-07T06:24:16Z,2024-10-10T11:54:58Z,,NONE,,"### Description

This pull request addresses issue #58977 by improving the handling of missing data in the `combine_first` method. The changes ensure that `None` values are replaced with `NaN`, which allows for better integration with other Pandas functions that expect `NaN` values.

### Related Issue
- Fixes #58977

### Checklist

- [x] Tests added and passed if fixing a bug or adding a new feature
- [x] All code checks passed","{'login': 'Lavishgangwani', 'id': 154001570, 'node_id': 'U_kgDOCS3gog', 'avatar_url': 'https://avatars.githubusercontent.com/u/154001570?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Lavishgangwani', 'html_url': 'https://github.com/Lavishgangwani', 'followers_url': 'https://api.github.com/users/Lavishgangwani/followers', 'following_url': 'https://api.github.com/users/Lavishgangwani/following{/other_user}', 'gists_url': 'https://api.github.com/users/Lavishgangwani/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Lavishgangwani/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Lavishgangwani/subscriptions', 'organizations_url': 'https://api.github.com/users/Lavishgangwani/orgs', 'repos_url': 'https://api.github.com/users/Lavishgangwani/repos', 'events_url': 'https://api.github.com/users/Lavishgangwani/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Lavishgangwani/received_events', 'type': 'User', 'site_admin': False}","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59987/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59987/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59987', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59987', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59987.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59987.patch', 'merged_at': None}"
10,https://api.github.com/repos/pandas-dev/pandas/issues/59977,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59977/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59977/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59977/events,https://github.com/pandas-dev/pandas/issues/59977,2568282267,I_kwDOAA0YD86ZFOCb,59977,ENH: Add support for generating 4-4-5 but by month not just quarter or year,"{'login': 'KuriaMaingi', 'id': 61688232, 'node_id': 'MDQ6VXNlcjYxNjg4MjMy', 'avatar_url': 'https://avatars.githubusercontent.com/u/61688232?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/KuriaMaingi', 'html_url': 'https://github.com/KuriaMaingi', 'followers_url': 'https://api.github.com/users/KuriaMaingi/followers', 'following_url': 'https://api.github.com/users/KuriaMaingi/following{/other_user}', 'gists_url': 'https://api.github.com/users/KuriaMaingi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/KuriaMaingi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/KuriaMaingi/subscriptions', 'organizations_url': 'https://api.github.com/users/KuriaMaingi/orgs', 'repos_url': 'https://api.github.com/users/KuriaMaingi/repos', 'events_url': 'https://api.github.com/users/KuriaMaingi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/KuriaMaingi/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2024-10-05T19:23:03Z,2024-10-11T06:30:39Z,,NONE,,"### Feature Type

- [X] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

Currently, you can generate quarters that fit the 4-4-5 fiscal calendar as is common in the retail world. [https://pandas.pydata.org/docs/reference/api/pandas.tseries.offsets.FY5253Quarter.html](url)

How can I generate a datetime index by month (generating a ""future"" dataframe for forecasting purposes) that matches the input data which is monthly & follows that 4-4-5 calendar?

For example, input data covers these time periods:
`['2020-07-05 00:00:00', '2020-08-02 00:00:00', '2020-08-30 00:00:00',
 '2020-10-04 00:00:00', '2020-11-01 00:00:00', '2020-11-29 00:00:00',
 '2021-01-03 00:00:00', '2021-01-31 00:00:00', '2021-02-28 00:00:00',
 '2021-04-04 00:00:00', '2021-05-02 00:00:00', '2021-05-30 00:00:00',
 '2021-07-04 00:00:00', '2021-08-01 00:00:00', '2021-08-29 00:00:00',
 '2021-10-03 00:00:00', '2021-10-31 00:00:00', '2021-11-28 00:00:00',
 '2022-01-02 00:00:00', '2022-01-30 00:00:00', '2022-02-27 00:00:00',
 '2022-04-03 00:00:00', '2022-05-01 00:00:00', '2022-05-29 00:00:00',
 '2022-07-03 00:00:00', '2022-07-31 00:00:00', '2022-08-28 00:00:00',
 '2022-10-02 00:00:00', '2022-10-30 00:00:00', '2022-11-27 00:00:00',
 '2023-01-01 00:00:00']`

 I can generate the quarters that match up with this frequency by using the following code:
`yoffset = pd.offsets.FY5253Quarter(weekday=6, startingMonth=8, variation=""last"")
yindex = pd.date_range('2020-08-30', periods=12, freq=yoffset)
yindex`

which in turn generates the correct output:
`DatetimeIndex(['2020-08-30', '2020-11-29', '2021-02-28', '2021-05-30',
               '2021-08-29', '2021-11-28', '2022-02-27', '2022-05-29',
               '2022-08-28', '2022-11-27', '2023-02-26', '2023-05-28'],
              dtype='datetime64[ns]', freq='REQ-L-AUG-SUN-1')`

How can I resample these quarterly periods to generate an equivalent 4-4-5 monthly frequency that follows the same ruleset?

### Feature Description

pd.offsets.FY5253Month(weekday=x, startingMonth=y, variation=""z)

### Alternative Solutions

Not aware of any and currently stuck

### Additional Context

_No response_",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59977/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59977/timeline,,,,
11,https://api.github.com/repos/pandas-dev/pandas/issues/59976,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59976/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59976/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59976/events,https://github.com/pandas-dev/pandas/issues/59976,2568026073,I_kwDOAA0YD86ZEPfZ,59976,DOC: Improve docs in the dt namespace,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 219960758, 'node_id': 'MDU6TGFiZWwyMTk5NjA3NTg=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Discussion', 'name': 'Needs Discussion', 'color': '207de5', 'default': False, 'description': 'Requires discussion from core team before further action'}]",open,False,,[],,2,2024-10-05T13:08:12Z,2024-10-08T22:21:23Z,,MEMBER,,"Ref: https://github.com/pandas-dev/pandas/pull/59878#discussion_r1788584918

E.g. https://pandas.pydata.org/docs/dev/reference/api/pandas.Series.dt.to_period.html

We currently copy the docstring from the underlying array method, which is at times either vague or incorrect as in the example above. We could instead override the docstring with custom value in `pandas/core/accessor.py` in the `_create_delegator_method` function. We would need a place to store the docstrings, and it would be a significant effort to add them all.

Possible approach: Create a new subdirectory, `pandas/core/docstrings/` for storing docstrings for purposes like this, and add `series_dt.py` there. It would contain a dictionary mapping the method name to the docstring.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59976/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59976/timeline,,,,
12,https://api.github.com/repos/pandas-dev/pandas/issues/59972,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59972/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59972/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59972/events,https://github.com/pandas-dev/pandas/pull/59972,2567554253,PR_kwDOAA0YD859rTGm,59972,DOC: Fix title capitalization in documentation files (#32550),"{'login': 'steeleelliott03', 'id': 100764769, 'node_id': 'U_kgDOBgGMYQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/100764769?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/steeleelliott03', 'html_url': 'https://github.com/steeleelliott03', 'followers_url': 'https://api.github.com/users/steeleelliott03/followers', 'following_url': 'https://api.github.com/users/steeleelliott03/following{/other_user}', 'gists_url': 'https://api.github.com/users/steeleelliott03/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/steeleelliott03/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/steeleelliott03/subscriptions', 'organizations_url': 'https://api.github.com/users/steeleelliott03/orgs', 'repos_url': 'https://api.github.com/users/steeleelliott03/repos', 'events_url': 'https://api.github.com/users/steeleelliott03/events{/privacy}', 'received_events_url': 'https://api.github.com/users/steeleelliott03/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-05T00:18:26Z,2024-10-05T00:18:26Z,,NONE,,"Corrected title capitalization in various .rst files to match the standard of capitalizing only the first word, unless a term like DataFrame or Series is involved.

Ran the  script to find and
correct heading issues in the following files:
- doc/source/user_guide/timedeltas.rst
- doc/source/whatsnew/v0.7.0.rst
- doc/source/whatsnew/v0.23.4.rst
- (… and so on)

Fixes part of issue #32550.

- [ ] closes #32550 
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59972/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59972/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59972', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59972', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59972.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59972.patch', 'merged_at': None}"
13,https://api.github.com/repos/pandas-dev/pandas/issues/59971,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59971/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59971/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59971/events,https://github.com/pandas-dev/pandas/pull/59971,2567203196,PR_kwDOAA0YD859qUuE,59971,BUG: fix #59950 handle duplicate column names in dataframe queries,"{'login': 'miguelcsx', 'id': 78029302, 'node_id': 'MDQ6VXNlcjc4MDI5MzAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/78029302?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/miguelcsx', 'html_url': 'https://github.com/miguelcsx', 'followers_url': 'https://api.github.com/users/miguelcsx/followers', 'following_url': 'https://api.github.com/users/miguelcsx/following{/other_user}', 'gists_url': 'https://api.github.com/users/miguelcsx/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/miguelcsx/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/miguelcsx/subscriptions', 'organizations_url': 'https://api.github.com/users/miguelcsx/orgs', 'repos_url': 'https://api.github.com/users/miguelcsx/repos', 'events_url': 'https://api.github.com/users/miguelcsx/events{/privacy}', 'received_events_url': 'https://api.github.com/users/miguelcsx/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-04T19:42:45Z,2024-10-08T13:22:45Z,,NONE,,"### Issue Description

When calling `DataFrame.query()` on a DataFrame with duplicate column names, an unexpected `TypeError` is raised due to a change introduced in pandas 2.2.1. The root cause is the `self.dtypes[k]` returning a Series for duplicate column names instead of a single value, leading to a failure in the query evaluation.

### Changes Made

- Fixed an issue where `Dataframe.query()` would throw an unexpected error

- The error was caused by `self.dtypes[k]`

- Adjusted the behavior to match the behavior prior to pandas version

- Added tests to ensure that `Dataframe.query()` works as expected

## PR Checklist

- [x] closes #59950
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59971/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59971/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59971', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59971', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59971.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59971.patch', 'merged_at': None}"
14,https://api.github.com/repos/pandas-dev/pandas/issues/59965,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59965/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59965/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59965/events,https://github.com/pandas-dev/pandas/issues/59965,2566138436,I_kwDOAA0YD86Y9CpE,59965,BUG: skipna=True operations don't skip NaN in FloatingArrays,"{'login': 'carlocastoldi', 'id': 34198340, 'node_id': 'MDQ6VXNlcjM0MTk4MzQw', 'avatar_url': 'https://avatars.githubusercontent.com/u/34198340?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/carlocastoldi', 'html_url': 'https://github.com/carlocastoldi', 'followers_url': 'https://api.github.com/users/carlocastoldi/followers', 'following_url': 'https://api.github.com/users/carlocastoldi/following{/other_user}', 'gists_url': 'https://api.github.com/users/carlocastoldi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/carlocastoldi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/carlocastoldi/subscriptions', 'organizations_url': 'https://api.github.com/users/carlocastoldi/orgs', 'repos_url': 'https://api.github.com/users/carlocastoldi/repos', 'events_url': 'https://api.github.com/users/carlocastoldi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/carlocastoldi/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyMzQy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Missing-data', 'name': 'Missing-data', 'color': 'd7e102', 'default': False, 'description': 'np.nan, pd.NaT, pd.NA, dropna, isnull, interpolate'}, {'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray', 'name': 'ExtensionArray', 'color': '6138b5', 'default': False, 'description': 'Extending pandas with custom dtypes or arrays.'}, {'id': 2365504383, 'node_id': 'MDU6TGFiZWwyMzY1NTA0Mzgz', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reduction%20Operations', 'name': 'Reduction Operations', 'color': '547c03', 'default': False, 'description': 'sum, mean, min, max, etc.'}, {'id': 6129961102, 'node_id': 'LA_kwDOAA0YD88AAAABbV_Ijg', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/PDEP%20missing%20values', 'name': 'PDEP missing values', 'color': 'fbca04', 'default': False, 'description': 'Issues that would be addressed by the Ice Cream Agreement from the Aug 2023 sprint'}]",open,False,,[],,2,2024-10-04T11:24:31Z,2024-10-09T05:39:06Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd

s1 = pd.Series({""a"": 0.0, ""b"": 1, ""c"": 1, ""d"": 0})
s2 = pd.Series({""a"": 0.0, ""b"": 2, ""c"": 2, ""d"": 2})
s3 = s1/s2
#display(s3)
s4 = s1.convert_dtypes()/s2.convert_dtypes()
#display(s4)
s5 = pd.Series([None,0.5,0.5,0]).convert_dtypes()
#display(s5)
s3.mean(skipna=True), s4.mean(skipna=True), s5.mean(skipna=True)
```


### Issue Description

Following #59961, I understand that series/dataframes of FloatingArrays cointaing `np.NaN` values are possible and meant to exists. These very same dataframes/series, however, fail to skip `NaN` values when asked to. The above examples outputs:
```
(np.float64(0.3333333333333333), <NA>, np.float64(0.3333333333333333))
```

### Expected Behavior

```
>>> s4.mean(skipna=True)
np.float64(0.3333333333333333)
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 139def2145b83d40364235c6297e1833eab7bb05
python                : 3.12.3
python-bits           : 64
OS                    : Linux
OS-release            : 6.8.0-41-generic
Version               : #41-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug  2 20:41:06 UTC 2024
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : en_GB.UTF-8
LOCALE                : en_GB.UTF-8

pandas                : 3.0.0.dev0+1545.g139def2145
numpy                 : 2.2.0.dev0+git20240930.3ee9e6a
dateutil              : 2.9.0.post0
pip                   : 24.0
Cython                : None
sphinx                : None
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pytz                  : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
xlsxwriter            : None
zstandard             : None
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None

</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59965/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59965/timeline,,,,
15,https://api.github.com/repos/pandas-dev/pandas/issues/59963,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59963/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59963/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59963/events,https://github.com/pandas-dev/pandas/pull/59963,2565996942,PR_kwDOAA0YD859mho8,59963,Fix API: astype method fails to raise errors for category data type,"{'login': 'HagonChan', 'id': 77165006, 'node_id': 'MDQ6VXNlcjc3MTY1MDA2', 'avatar_url': 'https://avatars.githubusercontent.com/u/77165006?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/HagonChan', 'html_url': 'https://github.com/HagonChan', 'followers_url': 'https://api.github.com/users/HagonChan/followers', 'following_url': 'https://api.github.com/users/HagonChan/following{/other_user}', 'gists_url': 'https://api.github.com/users/HagonChan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/HagonChan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/HagonChan/subscriptions', 'organizations_url': 'https://api.github.com/users/HagonChan/orgs', 'repos_url': 'https://api.github.com/users/HagonChan/repos', 'events_url': 'https://api.github.com/users/HagonChan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/HagonChan/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-04T10:09:06Z,2024-10-04T10:23:15Z,,NONE,,"- [x] closes #59899 (Replace xxxx with the GitHub issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59963/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59963/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59963', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59963', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59963.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59963.patch', 'merged_at': None}"
16,https://api.github.com/repos/pandas-dev/pandas/issues/59956,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59956/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59956/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59956/events,https://github.com/pandas-dev/pandas/issues/59956,2565553657,I_kwDOAA0YD86Y6z35,59956,ENH: Disable Numpy memory allocation while concat,"{'login': 'sandeyshc', 'id': 45159475, 'node_id': 'MDQ6VXNlcjQ1MTU5NDc1', 'avatar_url': 'https://avatars.githubusercontent.com/u/45159475?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sandeyshc', 'html_url': 'https://github.com/sandeyshc', 'followers_url': 'https://api.github.com/users/sandeyshc/followers', 'following_url': 'https://api.github.com/users/sandeyshc/following{/other_user}', 'gists_url': 'https://api.github.com/users/sandeyshc/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sandeyshc/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sandeyshc/subscriptions', 'organizations_url': 'https://api.github.com/users/sandeyshc/orgs', 'repos_url': 'https://api.github.com/users/sandeyshc/repos', 'events_url': 'https://api.github.com/users/sandeyshc/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sandeyshc/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info', 'name': 'Needs Info', 'color': '207de5', 'default': False, 'description': 'Clarification about behavior needed to assess issue'}]",open,False,,[],,7,2024-10-04T06:25:07Z,2024-10-11T20:18:05Z,,NONE,,"### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

We have sparse data with many null values, and while reading it using Pandas with PyArrow, it doesn't consume much memory because of pandas internal compression logic. However, during concatenation, NumPy allocates memory that isn't actually used, causing our Python script to fail due to memory allocation issues. Can you provide an option to disable NumPy memory allocation when concatenating DataFrames along axis=1?

### Feature Description

pd.concat(df_list,axis=1,numpy_allocation=False)

### Alternative Solutions

Atleast can you provide how can we change C++ script internally and use it for our purpose

### Additional Context

Please let me know if i am wrong.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59956/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59956/timeline,,,,
17,https://api.github.com/repos/pandas-dev/pandas/issues/59955,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59955/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59955/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59955/events,https://github.com/pandas-dev/pandas/pull/59955,2565217863,PR_kwDOAA0YD859kBS-,59955,DOCS: fix docstring validation errors for pandas.Series #59595,"{'login': 'd-urbonas', 'id': 110120780, 'node_id': 'U_kgDOBpBPTA', 'avatar_url': 'https://avatars.githubusercontent.com/u/110120780?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/d-urbonas', 'html_url': 'https://github.com/d-urbonas', 'followers_url': 'https://api.github.com/users/d-urbonas/followers', 'following_url': 'https://api.github.com/users/d-urbonas/following{/other_user}', 'gists_url': 'https://api.github.com/users/d-urbonas/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/d-urbonas/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/d-urbonas/subscriptions', 'organizations_url': 'https://api.github.com/users/d-urbonas/orgs', 'repos_url': 'https://api.github.com/users/d-urbonas/repos', 'events_url': 'https://api.github.com/users/d-urbonas/events{/privacy}', 'received_events_url': 'https://api.github.com/users/d-urbonas/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2024-10-04T00:53:30Z,2024-10-05T17:49:45Z,,NONE,,"Fixes the following issues from #59595 

-i ""pandas.Series.sparse.fill_value SA01"" \
-i ""pandas.Series.str.match RT03"" \ 

- [x] Partially addresses #59595 
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59955/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59955/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59955', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59955', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59955.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59955.patch', 'merged_at': None}"
18,https://api.github.com/repos/pandas-dev/pandas/issues/59954,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59954/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59954/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59954/events,https://github.com/pandas-dev/pandas/pull/59954,2565140689,PR_kwDOAA0YD859jw7E,59954,BUG: PeriodIndex.to_datetime inconsistent with its docstring,"{'login': 'aram-cinnamon', 'id': 97805700, 'node_id': 'U_kgDOBdRlhA', 'avatar_url': 'https://avatars.githubusercontent.com/u/97805700?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/aram-cinnamon', 'html_url': 'https://github.com/aram-cinnamon', 'followers_url': 'https://api.github.com/users/aram-cinnamon/followers', 'following_url': 'https://api.github.com/users/aram-cinnamon/following{/other_user}', 'gists_url': 'https://api.github.com/users/aram-cinnamon/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/aram-cinnamon/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/aram-cinnamon/subscriptions', 'organizations_url': 'https://api.github.com/users/aram-cinnamon/orgs', 'repos_url': 'https://api.github.com/users/aram-cinnamon/repos', 'events_url': 'https://api.github.com/users/aram-cinnamon/events{/privacy}', 'received_events_url': 'https://api.github.com/users/aram-cinnamon/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-03T23:15:01Z,2024-10-06T09:44:28Z,,CONTRIBUTOR,,"- [x] closes #59371
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59954/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59954/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59954', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59954', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59954.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59954.patch', 'merged_at': None}"
19,https://api.github.com/repos/pandas-dev/pandas/issues/59953,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59953/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59953/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59953/events,https://github.com/pandas-dev/pandas/issues/59953,2564147199,I_kwDOAA0YD86Y1cf_,59953,ENH: Is there a way to plot a long format data in matplotlib without pivoting the table ? ,"{'login': 'infinity-void6', 'id': 96457876, 'node_id': 'U_kgDOBb_UlA', 'avatar_url': 'https://avatars.githubusercontent.com/u/96457876?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/infinity-void6', 'html_url': 'https://github.com/infinity-void6', 'followers_url': 'https://api.github.com/users/infinity-void6/followers', 'following_url': 'https://api.github.com/users/infinity-void6/following{/other_user}', 'gists_url': 'https://api.github.com/users/infinity-void6/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/infinity-void6/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/infinity-void6/subscriptions', 'organizations_url': 'https://api.github.com/users/infinity-void6/orgs', 'repos_url': 'https://api.github.com/users/infinity-void6/repos', 'events_url': 'https://api.github.com/users/infinity-void6/events{/privacy}', 'received_events_url': 'https://api.github.com/users/infinity-void6/received_events', 'type': 'User', 'site_admin': False}","[{'id': 2413328, 'node_id': 'MDU6TGFiZWwyNDEzMzI4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Visualization', 'name': 'Visualization', 'color': '8AE234', 'default': False, 'description': 'plotting'}, {'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0NDUzNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question', 'name': 'Usage Question', 'color': '0052cc', 'default': False, 'description': None}, {'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info', 'name': 'Needs Info', 'color': '207de5', 'default': False, 'description': 'Clarification about behavior needed to assess issue'}, {'id': 2365504893, 'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate', 'name': 'Closing Candidate', 'color': 'be21f2', 'default': False, 'description': 'May be closeable, needs more eyeballs'}]",open,False,,[],,2,2024-10-03T13:59:42Z,2024-10-06T18:30:15Z,,NONE,,"### Feature Type

- [ ] Adding new functionality to pandas

- [ ] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

### Problem

I am currently reading this book called Hands On Data Analysis using Pandas by Stefie Molin. There are two formats of data, wide and long format data. The author uses pandas and matplotlib to plot a wide format data while uses seaborn package for the long format data. I tried searching in the web and it seems to be the custom. I tried asking gpt as well, and I can plot the long format data without seaborn too but it seems that I have to pivot the dataset. Is there a way around it .

Wide Data Frame Sample

date | TMAX | TMIN | TOBS
-- | -- | -- | --
2018-10-28 | 8.3 | 5.0 | 7.2
2018-10-04 | 22.8 | 11.7 | 11.7
2018-10-20 | 15.0 | -0.6 | 10.6
2018-10-24 | 16.7 | 4.4 | 6.7
2018-10-23 | 15.6 | -1.1 | 10.0

Long Data Frame Sample


date | datatype | value
-- | -- | --
2018-10-01 | TMAX | 21.1
2018-10-01 | TMIN | 8.9
2018-10-01 | TOBS | 13.9
2018-10-02 | TMAX | 23.9
2018-10-02 | TMIN | 13.9
2018-10-02 | TOBS | 17.2


Long Data Frame after pivoting

![image](https://github.com/user-attachments/assets/4eb22ed2-1e4f-4b40-be77-2b817f5573a7)



plot command for wide df
`ax = wide_df.plot(
    x='date',
    y=['TMAX', 'TMIN', 'TOBS'],
    figsize=(15, 5),
    title='Temperature in NYC in October 2018'
)
`
plot command for long df after pivot
`ax=long_df.pivot(index='date',columns='datatype',values='value')`
and apply a similar command as above


plot command for long_df with seaborn 
`ax=sns.lineplot(data=long_df,x='date',y='value',hue='datatype')`

Why isn't there a hue parameter or something similar in pandas for a long data format? My question can also be framed this way,
"" Why is pandas not enough for plotting? Why do I need external packages like matplotlib and seaborn to plot pandas data structure?"" 

Forgive me for my ignorance but I really want to know why cann't the features available in pandas and seaborn be available in pandas.

### Feature Description

Lets start with a hue feature in pandas for a long data format

### Alternative Solutions

we might have to pivot the table if we have to plot without using seaborn if we just need to use pandas

### Additional Context

_No response_",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59953/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59953/timeline,,,,
20,https://api.github.com/repos/pandas-dev/pandas/issues/59950,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59950/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59950/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59950/events,https://github.com/pandas-dev/pandas/issues/59950,2563513795,I_kwDOAA0YD86YzB3D,59950,BUG: DataFrame.query() throws error when df has duplicate column names,"{'login': 'ddenuyl-bebr', 'id': 151915448, 'node_id': 'U_kgDOCQ4LuA', 'avatar_url': 'https://avatars.githubusercontent.com/u/151915448?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ddenuyl-bebr', 'html_url': 'https://github.com/ddenuyl-bebr', 'followers_url': 'https://api.github.com/users/ddenuyl-bebr/followers', 'following_url': 'https://api.github.com/users/ddenuyl-bebr/following{/other_user}', 'gists_url': 'https://api.github.com/users/ddenuyl-bebr/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ddenuyl-bebr/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ddenuyl-bebr/subscriptions', 'organizations_url': 'https://api.github.com/users/ddenuyl-bebr/orgs', 'repos_url': 'https://api.github.com/users/ddenuyl-bebr/repos', 'events_url': 'https://api.github.com/users/ddenuyl-bebr/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ddenuyl-bebr/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 717120670, 'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue', 'name': 'good first issue', 'color': '0e8a16', 'default': True, 'description': None}, {'id': 1631985267, 'node_id': 'MDU6TGFiZWwxNjMxOTg1MjY3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/expressions', 'name': 'expressions', 'color': 'f3afff', 'default': False, 'description': 'pd.eval, query'}]",open,False,"{'login': 'miguelcsx', 'id': 78029302, 'node_id': 'MDQ6VXNlcjc4MDI5MzAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/78029302?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/miguelcsx', 'html_url': 'https://github.com/miguelcsx', 'followers_url': 'https://api.github.com/users/miguelcsx/followers', 'following_url': 'https://api.github.com/users/miguelcsx/following{/other_user}', 'gists_url': 'https://api.github.com/users/miguelcsx/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/miguelcsx/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/miguelcsx/subscriptions', 'organizations_url': 'https://api.github.com/users/miguelcsx/orgs', 'repos_url': 'https://api.github.com/users/miguelcsx/repos', 'events_url': 'https://api.github.com/users/miguelcsx/events{/privacy}', 'received_events_url': 'https://api.github.com/users/miguelcsx/received_events', 'type': 'User', 'site_admin': False}","[{'login': 'miguelcsx', 'id': 78029302, 'node_id': 'MDQ6VXNlcjc4MDI5MzAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/78029302?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/miguelcsx', 'html_url': 'https://github.com/miguelcsx', 'followers_url': 'https://api.github.com/users/miguelcsx/followers', 'following_url': 'https://api.github.com/users/miguelcsx/following{/other_user}', 'gists_url': 'https://api.github.com/users/miguelcsx/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/miguelcsx/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/miguelcsx/subscriptions', 'organizations_url': 'https://api.github.com/users/miguelcsx/orgs', 'repos_url': 'https://api.github.com/users/miguelcsx/repos', 'events_url': 'https://api.github.com/users/miguelcsx/events{/privacy}', 'received_events_url': 'https://api.github.com/users/miguelcsx/received_events', 'type': 'User', 'site_admin': False}, {'login': 'Asifussain', 'id': 93661420, 'node_id': 'U_kgDOBZUo7A', 'avatar_url': 'https://avatars.githubusercontent.com/u/93661420?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Asifussain', 'html_url': 'https://github.com/Asifussain', 'followers_url': 'https://api.github.com/users/Asifussain/followers', 'following_url': 'https://api.github.com/users/Asifussain/following{/other_user}', 'gists_url': 'https://api.github.com/users/Asifussain/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Asifussain/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Asifussain/subscriptions', 'organizations_url': 'https://api.github.com/users/Asifussain/orgs', 'repos_url': 'https://api.github.com/users/Asifussain/repos', 'events_url': 'https://api.github.com/users/Asifussain/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Asifussain/received_events', 'type': 'User', 'site_admin': False}]",,12,2024-10-03T09:07:39Z,2024-10-09T11:52:20Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({'a': range(3), 'b': range(3), 'c': range(3)}).rename(columns={'b': 'a'})
print(df.query('c == 1'))
```


### Issue Description

Since pandas 2.2.1 this throws an unexpected error:
`TypeError: dtype 'a    int64
a    int64
dtype: object' not understood`

This is because DataFrame.query() calls DataFrame.eval() which in turn calls DataFrame._get_cleaned_column_resolvers().

The dict comprehension in DataFrame._get_cleaned_column_resolvers() was changed in version 2.2.1.
version 2.2.0
```
return {
       clean_column_name(k): Series(
            v, copy=False, index=self.index, name=k
       ).__finalize__(self)
       for k, v in zip(self.columns, self._iter_column_arrays())
       if not isinstance(k, int)
 }
 ```
 
version 2.2.1
```
return {
            clean_column_name(k): Series(
                v, copy=False, index=self.index, name=k, dtype=self.dtypes[k]
            ).__finalize__(self)
            for k, v in zip(self.columns, self._iter_column_arrays())
            if not isinstance(k, int)
   }
   ```
   
   since the dtypes are now checked when the Series are created, this introduces the error described above, since for a duplicate
   column name self.dtypes[k] returns a Series instead of single value.


### Expected Behavior

1) I would expect either the behavior prior to v2.2.1 where the above example would return:
```
>>> df.query('c == 1')
   a  a  c
1  1  1  1
```
moreover, calling query() on column 'a' also works:
```
>>> df.query('a == 1')
   a  a  c
1  1  1  1
```
or
2) If above behavior is unwanted, I would except better error handling, smt like:
```
>>> df.query('c == 1')
DuplicateColumnError: DataFrame.query() is not supported for DataFrames with duplicate column names
```


### Installed Versions

INSTALLED VERSIONS
------------------
commit                : bdc79c146c2e32f2cab629be240f01658cfb6cc2
python                : 3.11.6.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 5.4.0-165-generic
Version               : #182-Ubuntu SMP Mon Oct 2 19:43:28 UTC 2023
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8
pandas                : 2.2.1
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.8.2
setuptools            : 69.1.1
pip                   : 23.0
Cython                : None
pytest                : 8.2.0
hypothesis            : 6.100.4
sphinx                : None
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 5.2.2
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.3
IPython               : None
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
gcsfs                 : None
matplotlib            : None
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : 0.19.2
pyarrow               : 15.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : None
sqlalchemy            : 2.0.27
tables                : None
tabulate              : 0.9.0
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59950/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59950/timeline,,,,
21,https://api.github.com/repos/pandas-dev/pandas/issues/59948,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59948/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59948/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59948/events,https://github.com/pandas-dev/pandas/pull/59948,2563181832,PR_kwDOAA0YD859dHgl,59948,Update html.py,"{'login': 'JustinCapili', 'id': 107870885, 'node_id': 'U_kgDOBm36pQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/107870885?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JustinCapili', 'html_url': 'https://github.com/JustinCapili', 'followers_url': 'https://api.github.com/users/JustinCapili/followers', 'following_url': 'https://api.github.com/users/JustinCapili/following{/other_user}', 'gists_url': 'https://api.github.com/users/JustinCapili/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JustinCapili/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JustinCapili/subscriptions', 'organizations_url': 'https://api.github.com/users/JustinCapili/orgs', 'repos_url': 'https://api.github.com/users/JustinCapili/repos', 'events_url': 'https://api.github.com/users/JustinCapili/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JustinCapili/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 13101118, 'node_id': 'MDU6TGFiZWwxMzEwMTExOA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Output-Formatting', 'name': 'Output-Formatting', 'color': 'ededed', 'default': False, 'description': '__repr__ of pandas objects, to_string'}]",open,False,,[],,0,2024-10-03T05:53:16Z,2024-10-05T13:15:29Z,,NONE,,"Adding a mathjax_ignore as a bug fix to ensure that proper formatting is performed

- [X] closes #59884  (Replace xxxx with the GitHub issue number)
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59948/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59948/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59948', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59948', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59948.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59948.patch', 'merged_at': None}"
22,https://api.github.com/repos/pandas-dev/pandas/issues/59947,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59947/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59947/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59947/events,https://github.com/pandas-dev/pandas/pull/59947,2562806464,PR_kwDOAA0YD859b4oy,59947,Update hist.py,"{'login': 'rraadd88', 'id': 9945034, 'node_id': 'MDQ6VXNlcjk5NDUwMzQ=', 'avatar_url': 'https://avatars.githubusercontent.com/u/9945034?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rraadd88', 'html_url': 'https://github.com/rraadd88', 'followers_url': 'https://api.github.com/users/rraadd88/followers', 'following_url': 'https://api.github.com/users/rraadd88/following{/other_user}', 'gists_url': 'https://api.github.com/users/rraadd88/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rraadd88/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rraadd88/subscriptions', 'organizations_url': 'https://api.github.com/users/rraadd88/orgs', 'repos_url': 'https://api.github.com/users/rraadd88/repos', 'events_url': 'https://api.github.com/users/rraadd88/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rraadd88/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-02T23:17:22Z,2024-10-03T16:12:01Z,,NONE,,"Minor improvement, allowing inference of the xlabel for a histgram plotted using a Series.

Reduces these lines of code:
```
ax=ds.hist()
ax.set(
    xlabel=ds.name,
)
``` 
to 
```
ds.hist()
``` 
---
- [NA] closes #xxxx (Replace xxxx with the GitHub issue number)
- [NA] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [NA] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [NA] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [NA] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59947/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59947/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59947', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59947', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59947.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59947.patch', 'merged_at': None}"
23,https://api.github.com/repos/pandas-dev/pandas/issues/59942,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59942/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59942/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59942/events,https://github.com/pandas-dev/pandas/pull/59942,2561946080,PR_kwDOAA0YD859Y9J0,59942,"Enhanced numeric.py to process hexadecimal,decimal,binary formats(0x 0o 0b…)","{'login': 'Lzforevr', 'id': 139556927, 'node_id': 'U_kgDOCFF4Pw', 'avatar_url': 'https://avatars.githubusercontent.com/u/139556927?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Lzforevr', 'html_url': 'https://github.com/Lzforevr', 'followers_url': 'https://api.github.com/users/Lzforevr/followers', 'following_url': 'https://api.github.com/users/Lzforevr/following{/other_user}', 'gists_url': 'https://api.github.com/users/Lzforevr/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Lzforevr/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Lzforevr/subscriptions', 'organizations_url': 'https://api.github.com/users/Lzforevr/orgs', 'repos_url': 'https://api.github.com/users/Lzforevr/repos', 'events_url': 'https://api.github.com/users/Lzforevr/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Lzforevr/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2024-10-02T15:05:50Z,2024-10-02T15:27:51Z,,NONE,,"
- [x] closes #59207 (Replace xxxx with the GitHub issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59942/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59942/timeline,,,True,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59942', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59942', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59942.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59942.patch', 'merged_at': None}"
24,https://api.github.com/repos/pandas-dev/pandas/issues/59937,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59937/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59937/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59937/events,https://github.com/pandas-dev/pandas/pull/59937,2561181331,PR_kwDOAA0YD859W2ag,59937,Backport PR #59906 on branch 2.3.x (BLD: Fix armv7 build),"{'login': 'meeseeksmachine', 'id': 39504233, 'node_id': 'MDQ6VXNlcjM5NTA0MjMz', 'avatar_url': 'https://avatars.githubusercontent.com/u/39504233?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/meeseeksmachine', 'html_url': 'https://github.com/meeseeksmachine', 'followers_url': 'https://api.github.com/users/meeseeksmachine/followers', 'following_url': 'https://api.github.com/users/meeseeksmachine/following{/other_user}', 'gists_url': 'https://api.github.com/users/meeseeksmachine/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/meeseeksmachine/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/meeseeksmachine/subscriptions', 'organizations_url': 'https://api.github.com/users/meeseeksmachine/orgs', 'repos_url': 'https://api.github.com/users/meeseeksmachine/repos', 'events_url': 'https://api.github.com/users/meeseeksmachine/events{/privacy}', 'received_events_url': 'https://api.github.com/users/meeseeksmachine/received_events', 'type': 'User', 'site_admin': False}","[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNTA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Build', 'name': 'Build', 'color': '75507B', 'default': False, 'description': 'Library building on various platforms'}, {'id': 2628846204, 'node_id': 'MDU6TGFiZWwyNjI4ODQ2MjA0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ARM', 'name': 'ARM', 'color': 'c2e0c6', 'default': False, 'description': 'aarch64 architecture'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/119', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/119/labels', 'id': 11466880, 'node_id': 'MI_kwDOAA0YD84ArviA', 'number': 119, 'title': '2.3', 'description': 'on-merge: backport to 2.3.x', 'creator': {'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 35, 'closed_issues': 82, 'state': 'open', 'created_at': '2024-08-20T19:39:44Z', 'updated_at': '2024-10-11T08:07:10Z', 'due_on': None, 'closed_at': None}",0,2024-10-02T10:12:35Z,2024-10-03T07:41:15Z,,CONTRIBUTOR,,Backport PR #59906: BLD: Fix armv7 build,,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59937/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59937/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59937', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59937', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59937.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59937.patch', 'merged_at': None}"
25,https://api.github.com/repos/pandas-dev/pandas/issues/59935,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59935/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59935/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59935/events,https://github.com/pandas-dev/pandas/pull/59935,2560968766,PR_kwDOAA0YD859WH1R,59935,Handling conversion of empty categorical with dtype_backend='pyarrow',"{'login': 'veljanin', 'id': 36128327, 'node_id': 'MDQ6VXNlcjM2MTI4MzI3', 'avatar_url': 'https://avatars.githubusercontent.com/u/36128327?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/veljanin', 'html_url': 'https://github.com/veljanin', 'followers_url': 'https://api.github.com/users/veljanin/followers', 'following_url': 'https://api.github.com/users/veljanin/following{/other_user}', 'gists_url': 'https://api.github.com/users/veljanin/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/veljanin/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/veljanin/subscriptions', 'organizations_url': 'https://api.github.com/users/veljanin/orgs', 'repos_url': 'https://api.github.com/users/veljanin/repos', 'events_url': 'https://api.github.com/users/veljanin/events{/privacy}', 'received_events_url': 'https://api.github.com/users/veljanin/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUyNzM1Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Categorical', 'name': 'Categorical', 'color': 'e11d21', 'default': False, 'description': 'Categorical Data Type'}]",open,False,,[],,5,2024-10-02T08:33:57Z,2024-10-10T15:34:32Z,,NONE,,"Handling the case where conversion of empty categorical series with specified dtype_backend='pyarrow' in convert_dtypes function results in 1) an error (when there are no defined categories) or 2) in null[pyarrow] dtype (when there are some defined categories).

- [x] Tests added and passed
- [x] Closes #59934 
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59935/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59935/timeline,,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/59935', 'html_url': 'https://github.com/pandas-dev/pandas/pull/59935', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/59935.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/59935.patch', 'merged_at': None}"
26,https://api.github.com/repos/pandas-dev/pandas/issues/59934,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59934/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59934/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59934/events,https://github.com/pandas-dev/pandas/issues/59934,2560944506,I_kwDOAA0YD86YpOl6,59934,BUG: Trying to use convert_dtypes with dtype_backend='pyarrow' specified on empty categorical series results in error or null[pyarrow] dtype,"{'login': 'veljanin', 'id': 36128327, 'node_id': 'MDQ6VXNlcjM2MTI4MzI3', 'avatar_url': 'https://avatars.githubusercontent.com/u/36128327?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/veljanin', 'html_url': 'https://github.com/veljanin', 'followers_url': 'https://api.github.com/users/veljanin/followers', 'following_url': 'https://api.github.com/users/veljanin/following{/other_user}', 'gists_url': 'https://api.github.com/users/veljanin/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/veljanin/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/veljanin/subscriptions', 'organizations_url': 'https://api.github.com/users/veljanin/orgs', 'repos_url': 'https://api.github.com/users/veljanin/repos', 'events_url': 'https://api.github.com/users/veljanin/events{/privacy}', 'received_events_url': 'https://api.github.com/users/veljanin/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUyNzM1Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Categorical', 'name': 'Categorical', 'color': 'e11d21', 'default': False, 'description': 'Categorical Data Type'}, {'id': 3303158446, 'node_id': 'MDU6TGFiZWwzMzAzMTU4NDQ2', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Arrow', 'name': 'Arrow', 'color': 'f9d0c4', 'default': False, 'description': 'pyarrow functionality'}]",open,False,,[],,0,2024-10-02T08:22:10Z,2024-10-02T21:04:49Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import pandas as pd

# example 1
ser1 = pd.Series(pd.Categorical([None] * 5))
converted1 = ser1.convert_dtypes(dtype_backend=""pyarrow"")

# example 2
ser2 = pd.Series(pd.Categorical([None] * 5, categories=[""S1"", ""S2""]))
converted2 = ser2.convert_dtypes(dtype_backend=""pyarrow"")
```


### Issue Description

Trying to convert categorical series with empty categories results in `pyarrow.lib.ArrowNotImplementedError: NumPyConverter doesn't implement <null> conversion. `.
Trying to convert categorical series with non-empty categories returns null[pyarrow] dtype.

This is inconsistent with regular behavior when converting categoricals - if series is not empty, convert_dtypes call returns categorical dtype (essentially ignoring the requested pyarrow backend conversion).

I encountered this issue when trying to read files (like parquet, spss, ...) where some categorical variables are empty...

### Expected Behavior

Returning categorical dtype with propagated categories, and not raising errors.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 00855f81bd84cc6ed9ae42c5f66916b2208dbe04
python                : 3.12.0
python-bits           : 64
OS                    : Windows
OS-release            : 11
Version               : 10.0.22631
machine               : AMD64
processor             : Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : English_United States.1252
pandas                : 3.0.0.dev0+1536.g00855f81bd
numpy                 : 1.26.4
dateutil              : 2.9.0.post0
pip                   : 24.2
Cython                : 3.0.11
sphinx                : 8.0.2
IPython               : 8.27.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
blosc                 : None
bottleneck            : 1.4.0
fastparquet           : 2024.5.0
fsspec                : 2024.9.0
html5lib              : 1.1
hypothesis            : 6.112.2
gcsfs                 : 2024.9.0post1
jinja2                : 3.1.4
lxml.etree            : 5.3.0
matplotlib            : 3.9.2
numba                 : 0.60.0
numexpr               : 2.10.1
odfpy                 : None
openpyxl              : 3.1.5
psycopg2              : 2.9.9
pymysql               : 1.4.6
pyarrow               : 17.0.0
pyreadstat            : 1.2.7
pytest                : 8.3.3
python-calamine       : None
pytz                  : 2024.2
pyxlsb                : 1.0.10
s3fs                  : 2024.9.0
scipy                 : 1.14.1
sqlalchemy            : 2.0.35
tables                : 3.10.1
tabulate              : 0.9.0
xarray                : 2024.9.0
xlrd                  : 2.0.1
xlsxwriter            : 3.2.0
zstandard             : 0.23.0
tzdata                : 2024.2
qtpy                  : None
pyqt5                 : None

</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59934/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59934/timeline,,,,
27,https://api.github.com/repos/pandas-dev/pandas/issues/59933,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59933/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59933/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59933/events,https://github.com/pandas-dev/pandas/issues/59933,2560390330,I_kwDOAA0YD86YnHS6,59933,BUG: locset with Series as column key fails inconsistently,"{'login': 'sfc-gh-rdurrani', 'id': 149019786, 'node_id': 'U_kgDOCOHcig', 'avatar_url': 'https://avatars.githubusercontent.com/u/149019786?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sfc-gh-rdurrani', 'html_url': 'https://github.com/sfc-gh-rdurrani', 'followers_url': 'https://api.github.com/users/sfc-gh-rdurrani/followers', 'following_url': 'https://api.github.com/users/sfc-gh-rdurrani/following{/other_user}', 'gists_url': 'https://api.github.com/users/sfc-gh-rdurrani/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sfc-gh-rdurrani/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sfc-gh-rdurrani/subscriptions', 'organizations_url': 'https://api.github.com/users/sfc-gh-rdurrani/orgs', 'repos_url': 'https://api.github.com/users/sfc-gh-rdurrani/repos', 'events_url': 'https://api.github.com/users/sfc-gh-rdurrani/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sfc-gh-rdurrani/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}]",open,False,,[],,2,2024-10-01T23:40:51Z,2024-10-05T22:50:57Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
>>> import pandas as pd

>>> df = pd.DataFrame([[1, 2, 3], [4, 5, 6]], columns=list(""ABC""))

>>>  df.loc[:, pd.Series(['A', 'C'])] = pd.Series([10, 20, 30]) # succeeds

>>> df
    A  B   C
0  10  2  20
1  10  5  20

>>> df.loc[:, pd.Series(['A', 'B', 'C'])] = pd.Series([10, 20, 30]) # fails
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/internals/blocks.py:1429, in Block.setitem(self, indexer, value, using_cow)
   1428 try:
-> 1429     values[indexer] = casted
   1430 except (TypeError, ValueError) as err:

ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (2,3)

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Cell In[5], line 1
----> 1 df.loc[:, pd.Series(['A', 'B',  'C'])] = pd.Series([10, 20, 30])

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/indexing.py:911, in _LocationIndexer.__setitem__(self, key, value)
    908 self._has_valid_setitem_indexer(key)
    910 iloc = self if self.name == ""iloc"" else self.obj.iloc
--> 911 iloc._setitem_with_indexer(indexer, value, self.name)

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/indexing.py:1944, in _iLocIndexer._setitem_with_indexer(self, indexer, value, name)
   1942     self._setitem_with_indexer_split_path(indexer, value, name)
   1943 else:
-> 1944     self._setitem_single_block(indexer, value, name)

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/indexing.py:2218, in _iLocIndexer._setitem_single_block(self, indexer, value, name)
   2215 self.obj._check_is_chained_assignment_possible()
   2217 # actually do the set
-> 2218 self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
   2219 self.obj._maybe_update_cacher(clear=True, inplace=True)

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/internals/managers.py:415, in BaseBlockManager.setitem(self, indexer, value, warn)
    411     # No need to split if we either set all columns or on a single block
    412     # manager
    413     self = self.copy()
--> 415 return self.apply(""setitem"", indexer=indexer, value=value)

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/internals/managers.py:363, in BaseBlockManager.apply(self, f, align_keys, **kwargs)
    361         applied = b.apply(f, **kwargs)
    362     else:
--> 363         applied = getattr(b, f)(**kwargs)
    364     result_blocks = extend_blocks(applied, result_blocks)
    366 out = type(self).from_blocks(result_blocks, self.axes)

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/internals/blocks.py:1432, in Block.setitem(self, indexer, value, using_cow)
   1430     except (TypeError, ValueError) as err:
   1431         if is_list_like(casted):
-> 1432             raise ValueError(
   1433                 ""setting an array element with a sequence.""
   1434             ) from err
   1435         raise
   1436 return self

ValueError: setting an array element with a sequence.

>>> In [7]: df.loc[:, pd.Series(['A'])] = pd.Series([10, 20, 30]) # Fails
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/internals/blocks.py:1429, in Block.setitem(self, indexer, value, using_cow)
   1428 try:
-> 1429     values[indexer] = casted
   1430 except (TypeError, ValueError) as err:

ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (2,1)

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Cell In[7], line 1
----> 1 df.loc[:, pd.Series(['A'])] = pd.Series([10, 20, 30])

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/indexing.py:911, in _LocationIndexer.__setitem__(self, key, value)
    908 self._has_valid_setitem_indexer(key)
    910 iloc = self if self.name == ""iloc"" else self.obj.iloc
--> 911 iloc._setitem_with_indexer(indexer, value, self.name)

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/indexing.py:1944, in _iLocIndexer._setitem_with_indexer(self, indexer, value, name)
   1942     self._setitem_with_indexer_split_path(indexer, value, name)
   1943 else:
-> 1944     self._setitem_single_block(indexer, value, name)

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/indexing.py:2218, in _iLocIndexer._setitem_single_block(self, indexer, value, name)
   2215 self.obj._check_is_chained_assignment_possible()
   2217 # actually do the set
-> 2218 self.obj._mgr = self.obj._mgr.setitem(indexer=indexer, value=value)
   2219 self.obj._maybe_update_cacher(clear=True, inplace=True)

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/internals/managers.py:415, in BaseBlockManager.setitem(self, indexer, value, warn)
    411     # No need to split if we either set all columns or on a single block
    412     # manager
    413     self = self.copy()
--> 415 return self.apply(""setitem"", indexer=indexer, value=value)

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/internals/managers.py:363, in BaseBlockManager.apply(self, f, align_keys, **kwargs)
    361         applied = b.apply(f, **kwargs)
    362     else:
--> 363         applied = getattr(b, f)(**kwargs)
    364     result_blocks = extend_blocks(applied, result_blocks)
    366 out = type(self).from_blocks(result_blocks, self.axes)

File ~/.miniconda3/envs/snowpark/lib/python3.10/site-packages/pandas/core/internals/blocks.py:1432, in Block.setitem(self, indexer, value, using_cow)
   1430     except (TypeError, ValueError) as err:
   1431         if is_list_like(casted):
-> 1432             raise ValueError(
   1433                 ""setting an array element with a sequence.""
   1434             ) from err
   1435         raise
   1436 return self

ValueError: setting an array element with a sequence

>>> df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=list(""ABC""))

>>> df.loc[:, pd.Series(['A', 'B', 'C'])] = pd.Series([10, 20, 30]) # Succeeds

>>> df
    A   B   C
0  10  20  30
1  10  20  30
2  10  20  30
```


### Issue Description

It seems that we can only provide as many column indexers in the Series key for the column as are rows, but all of the above examples should succeed.

### Expected Behavior

Columns that are indexed should be set with the corresponding value (determined by position).

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : bdc79c146c2e32f2cab629be240f01658cfb6cc2
python                : 3.10.14.final.0
python-bits           : 64
OS                    : Darwin
OS-release            : 23.6.0
Version               : Darwin Kernel Version 23.6.0: Mon Jul 29 21:13:04 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6020
machine               : arm64
processor             : arm
byteorder             : little
LC_ALL                : None
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.1
numpy                 : 1.26.4
pytz                  : 2024.1
dateutil              : 2.9.0.post0
setuptools            : 72.1.0
pip                   : 24.2
Cython                : None
pytest                : 7.4.4
hypothesis            : None
sphinx                : 5.0.2
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : None
html5lib              : None
pymysql               : None
psycopg2              : None
jinja2                : 3.1.4
IPython               : 8.27.0
pandas_datareader     : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.12.3
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2024.6.1
gcsfs                 : None
matplotlib            : 3.9.2
numba                 : None
numexpr               : None
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : None
pyarrow               : 17.0.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.14.1
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : None
zstandard             : None
tzdata                : 2024.1
qtpy                  : None
pyqt5                 : None

</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59933/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59933/timeline,,,,
28,https://api.github.com/repos/pandas-dev/pandas/issues/59932,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59932/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59932/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59932/events,https://github.com/pandas-dev/pandas/issues/59932,2559779205,I_kwDOAA0YD86YkyGF,59932,BUG: np.nan_to_num change pandas DataFrame in place when copy = True ,"{'login': 'lil-blue-curve', 'id': 183429179, 'node_id': 'U_kgDOCu7oOw', 'avatar_url': 'https://avatars.githubusercontent.com/u/183429179?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/lil-blue-curve', 'html_url': 'https://github.com/lil-blue-curve', 'followers_url': 'https://api.github.com/users/lil-blue-curve/followers', 'following_url': 'https://api.github.com/users/lil-blue-curve/following{/other_user}', 'gists_url': 'https://api.github.com/users/lil-blue-curve/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/lil-blue-curve/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/lil-blue-curve/subscriptions', 'organizations_url': 'https://api.github.com/users/lil-blue-curve/orgs', 'repos_url': 'https://api.github.com/users/lil-blue-curve/repos', 'events_url': 'https://api.github.com/users/lil-blue-curve/events{/privacy}', 'received_events_url': 'https://api.github.com/users/lil-blue-curve/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 76865106, 'node_id': 'MDU6TGFiZWw3Njg2NTEwNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Compat', 'name': 'Compat', 'color': '0052cc', 'default': False, 'description': 'pandas objects compatability with Numpy or Python functions'}]",open,False,,[],,1,2024-10-01T17:07:38Z,2024-10-01T21:03:57Z,,NONE,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.


### Reproducible Example

```python
import numpy as np
import pandas as pd

x = pd.DataFrame([np.nan])
np.nan_to_num(x, copy=True)
print(x)
```


### Issue Description

Result x is changed to 0.0 even when nan_to_num is called with copy=True.

This issue is originally reported to numpy [here](https://github.com/numpy/numpy/issues/27487). Looks like pandas ignores `copy=True` NumPy passes?

### Expected Behavior

x should not be changed when copy=True.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit                : 0691c5cf90477d3503834d983f69350f250a6ff7
python                : 3.11.8
python-bits           : 64
OS                    : Linux
OS-release            : 5.10.0-smp-1100.466.602.1
Version               : #1 [v5.10.0-1100.466.602.1] SMP @1708156698
machine               : x86_64
processor             : 
byteorder             : little
LC_ALL                : None
LANG                  : None
LOCALE                : en_US.UTF-8

pandas                : 2.2.3
numpy                 : 2.1.1
pytz                  : 2024.1
dateutil              : 2.8.1
pip                   : None
Cython                : None
sphinx                : None
IPython               : None
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : None
blosc                 : None
bottleneck            : None
dataframe-api-compat  : None
fastparquet           : None
fsspec                : None
html5lib              : None
hypothesis            : None
gcsfs                 : None
jinja2                : None
lxml.etree            : 5.3.0
matplotlib            : None
numba                 : None
numexpr               : 2.8.7
odfpy                 : None
openpyxl              : 3.1.2
pandas_gbq            : None
psycopg2              : None
pymysql               : None
pyarrow               : None
pyreadstat            : None
pytest                : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.13.1
sqlalchemy            : None
tables                : None
tabulate              : None
xarray                : None
xlrd                  : 2.0.1
xlsxwriter            : None
zstandard             : None
tzdata                : None
qtpy                  : None
pyqt5                 : None

</details>
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59932/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59932/timeline,,,,
29,https://api.github.com/repos/pandas-dev/pandas/issues/59931,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/59931/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/59931/comments,https://api.github.com/repos/pandas-dev/pandas/issues/59931/events,https://github.com/pandas-dev/pandas/issues/59931,2559117094,I_kwDOAA0YD86YiQcm,59931,ENH: Add support to customize time format and more detailed error handling information for to_time,"{'login': 'Lzforevr', 'id': 139556927, 'node_id': 'U_kgDOCFF4Pw', 'avatar_url': 'https://avatars.githubusercontent.com/u/139556927?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Lzforevr', 'html_url': 'https://github.com/Lzforevr', 'followers_url': 'https://api.github.com/users/Lzforevr/followers', 'following_url': 'https://api.github.com/users/Lzforevr/following{/other_user}', 'gists_url': 'https://api.github.com/users/Lzforevr/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Lzforevr/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Lzforevr/subscriptions', 'organizations_url': 'https://api.github.com/users/Lzforevr/orgs', 'repos_url': 'https://api.github.com/users/Lzforevr/repos', 'events_url': 'https://api.github.com/users/Lzforevr/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Lzforevr/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2024-10-01T12:44:14Z,2024-10-07T06:36:15Z,,NONE,,"### Feature Type

- [ ] Adding new functionality to pandas

- [X] Changing existing functionality in pandas

- [ ] Removing existing functionality in pandas


### Problem Description

**Path:** pandas/core/tools/times.py
**Func:** to_time

  Though to_time is able to handle several common time formats, I still wish to enhance its versatility and adaptability by customizing time format. By the way, customized error handling infos are also of use (though simple).

  It's my pleasure if you agree with my changes and I'd love to make PR!


### Feature Description

I've modified **times.py** for the above enhancements, and I've made a test demo to show its new feature in **times_test.py**. 
1. Improved compatibility: Allows users to customize the time format, which improves the versatility and adaptability of the function.
2. Enhanced error handling: Provide more detailed error information for easy debugging and problem location.



### Alternative Solutions

The source code are as follows:

1. new times.py
``` python 
# modfied times.py
from __future__ import annotations
from datetime import datetime, time
from typing import TYPE_CHECKING, List, Union
import numpy as np
from pandas._libs.lib import is_list_like
from pandas.core.dtypes.generic import ABCIndex, ABCSeries
from pandas.core.dtypes.missing import notna

if TYPE_CHECKING:
    from pandas._typing import DateTimeErrorChoices


def to_time(
        arg,
        format: Union[str, List[str], None] = None,
        infer_time_format: bool = False,
        errors: DateTimeErrorChoices = ""raise"",
        custom_formats: List[str] = None,
):
    """"""
Parse time strings to time objects using fixed strptime formats (""%H:%M"",
""%H%M"", ""%I:%M%p"", ""%I%M%p"", ""%H:%M:%S"", ""%H%M%S"", ""%I:%M:%S%p"",
""%I%M%S%p"") and additional custom formats.

Use infer_time_format if all the strings are in the same format to speed
up conversion.

Parameters
----------
arg : string in time format, datetime.time, list, tuple, 1-d array, Series
format : str or list of str, default None
    Format(s) used to convert arg into a time object. If None, fixed
    formats are used.
infer_time_format: bool, default False
    Infer the time format based on the first non-NaN element. If all
    strings are in the same format, this will speed up conversion.
errors : {'raise', 'coerce'}, default 'raise'
    - If 'raise', then invalid parsing will raise an exception
    - If 'coerce', then invalid parsing will be set as None
custom_formats : list of str, default None
    Additional custom time formats to use.
Returns
-------
datetime.time or list of datetime.time
""""""
    if errors not in (""raise"", ""coerce""):
        raise ValueError(""errors must be one of 'raise', or 'coerce'."")

    def _convert_listlike(arg, format):
        if isinstance(arg, (list, tuple)):
            arg = np.array(arg, dtype=""O"")

        elif getattr(arg, ""ndim"", 1) > 1:
            raise TypeError(
                ""arg must be a string, datetime, list, tuple, 1-d array, or Series""
            )
        arg = np.asarray(arg, dtype=""O"")

        if infer_time_format and format is None:
            format = _guess_time_format_for_array(arg)
        times = []
        if format is not None:
            if isinstance(format, list):
                for element in arg:
                    for fmt in format:
                        try:
                            times.append(datetime.strptime(element, fmt).time())
                            break
                        except (ValueError, TypeError):
                            continue
                    else:
                        if errors == ""raise"":
                            msg = (
                                f""Cannot convert {element} to a time with given ""f""formats {format}"")
                            raise ValueError(msg)
                        times.append(None)
            else:
                for element in arg:
                    try:
                        times.append(datetime.strptime(element, format).time())
                    except (ValueError, TypeError) as err:
                        if errors == ""raise"":
                            msg = (f""Cannot convert {element} to a time withgiven ""f""format {format}"")
                            raise ValueError(msg) from err
                        times.append(None)
        else:
            formats = _time_formats + (custom_formats or [])
            for element in arg:
                time_object = None
                try:
                    time_object = time.fromisoformat(element)
                except (ValueError, TypeError):
                    for time_format in formats:
                        try:
                            time_object = datetime.strptime(element, time_format).time()
                            break
                        except (ValueError, TypeError):
                            continue
                if time_object is not None:
                    times.append(time_object)
                elif errors == ""raise"":
                    raise ValueError(f""Cannot convert arg {arg} to a time"")
                else:
                    times.append(None)
        return times

    if arg is None:
        return arg
    elif isinstance(arg, time):
        return arg
    elif isinstance(arg, ABCSeries):
        values = _convert_listlike(arg._values, format)
        return arg._constructor(values, index=arg.index, name=arg.name)
    elif isinstance(arg, ABCIndex):
        return _convert_listlike(arg, format)
    elif is_list_like(arg):
        return _convert_listlike(arg, format)
    return _convert_listlike(np.array([arg]), format)[0]


# Fixed time formats for time parsing
_time_formats = [
    ""%H:%M"",
    ""%H%M"",
    ""%I:%M%p"",
    ""%I%M%p"",
    ""%H:%M:%S"",
    ""%H%M%S"",
    ""%I:%M:%S%p"",
    ""%I%M%S%p"",
]


def _guess_time_format_for_array(arr):
    # Try to guess the format based on the first non-NaN element
    non_nan_elements = notna(arr).nonzero()[0]
    if len(non_nan_elements):
        element = arr[non_nan_elements[0]]
        for time_format in _time_formats:
            try:
                datetime.strptime(element, time_format)
                return time_format
            except ValueError:
                pass
    return None

```
2. test demo (under the same directory of times.py)
``` python
# times_test.py
from datetime import time

import pandas as pd
import numpy as np
from times import to_time


# Test code
def test_to_time():
    """"""
    - Tests the `to_time` function with various input formats
    and demonstrates how it handles invalid inputs.
    - return: None
    """"""
    # Single time string
    single_time_str = ""12:30""
    print(""Single time string:"", to_time(single_time_str))
    # Time object
    time_obj = time(12, 30)
    print(""Time object:"", to_time(time_obj))
    # List of time strings
    time_list = [""12:30"", ""13:45""]
    print(""List of time strings:"", to_time(time_list))
    # NumPy array of time strings
    time_array = np.array([""12:30"", ""13:45""])
    print(""NumPy array of time strings:"", to_time(time_array))
    # Pandas Series of time strings
    time_series = pd.Series([""12:30"", ""13:45""])
    print(""Pandas Series of time strings:"", to_time(time_series))

    # Error handling
    invalid_list = [""12:30"", ""invalid""]
    try:
        print(""Invalid list:"", to_time(invalid_list))
    except ValueError as e:
        print(""Error:"", e)

    # Error handling (coerce)
    invalid_list_coerce = [""12:30"", ""invalid""]
    print(""Invalid list (coerce):"", to_time(invalid_list_coerce, errors=""coerce""))
    # Custom format
    custom_format = [""%H:%M:%S.%f""]
    custom_time_list = [""12:30:45.123456"", ""13:45:00.987654""]
    print(""Custom time list:"", to_time(custom_time_list, custom_formats=custom_format))
    # Inferred time list
    inferred_time_list = [""12:30"", ""13:45""]
    print(""Inferred time list:"", to_time(inferred_time_list, infer_time_format=True))
    # ISO 8601 time list
    iso_time_list = [""12:30:45"", ""13:45:00""]
    print(""ISO 8601 time list:"", to_time(iso_time_list))


test_to_time()
```
3. result for times_test.py
``` bash
Single time string: 12:30:00
Time object: 12:30:00
List of time strings: [datetime.time(12, 30), datetime.time(13, 45)]
NumPy array of time strings: [datetime.time(12, 30), datetime.time(13, 45)]
Pandas Series of time strings: 0    12:30:00
1    13:45:00
dtype: object
Error: Cannot convert arg ['12:30' 'invalid'] to a time
Invalid list (coerce): [datetime.time(12, 30), None]
Custom time list: [datetime.time(12, 30, 45, 123456), datetime.time(13, 45, 0, 987654)]
Inferred time list: [datetime.time(12, 30), datetime.time(13, 45)]
ISO 8601 time list: [datetime.time(12, 30, 45), datetime.time(13, 45)]
```

### Additional Context

_No response_",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/59931/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/59931/timeline,,,,
